### ISSUE TITLE
Poor performance of the trained model

### ISSUE THREAD

**Issue by MoxinC** [WING-NUS/sequicity#18]
Hi, 

I ran the test script with the released trained model
```
python model.py -mode test -model [tsdf-camrest|tsdf-kvret]
```
and get the following results:
```
bleu_metric bleu	0.06684825751851149
match_metric match	(0.8059701491935842, 0.0)
success_f1_metric success	0.8063241056772681
```

The results seem be much poorer than those listed in the paper. Is there anything wrong with the trained model, or my misoperation?

Another problem is that I ran the test script several times but get one of the following two results. Shouldn't it return the same results every time?
```
bleu_metric bleu	0.0667021664320532
match_metric match	(0.8059701491935842, 0.0)
success_f1_metric success	0.8039603910437605

bleu_metric bleu	0.06684825751851149
match_metric match	(0.8059701491935842, 0.0)
success_f1_metric success	0.8063241056772681
```

**Comment by shizhediao** [comment]
Hi, we uploaded the wrong vocab.txt file in that version which led to the poor performance.
Now the up-to-date version with the correct trained model has been uploaded.
Please test it and any problems please let us know.

For the second problem, I don't think there is a huge difference between these two results(the difference lies within 0.001). In my opinion, it may be caused by the machine floating point calculation.
